### ISSUE TITLE
themedContext is missing

### ISSUE THREAD

**Issue by joonseolee** [kth9192/CamerakitSample#1]
```kotlin
...
        capture.setOnClickListener {
                    camera.captureImage(cameraKitUtil.getCallback(themedContext))
        }
...
```

안녕하세요 안드로이드에 대해 접한지 얼마되지않았는데 MainActivity 에 18번라인 themedContext 가 뭔지 모르겠더라군요...
혹시 무엇인지 알수있을까요?

**Comment by kth9192** [comment]
안녕하세요. 현재 안드로이드를 하고 있지 않아 정확한 답변이 될지는 모르겠지만,

당시에 코딩을 할때 여러 컨텍스트를 넣어보려고 작업하다가 들어간 것으로 기억합니다.
아마 다른 컨텍스트를 적용해도 될 것 같습니다.

2019년 9월 5일 (목) 오전 11:41, Joon-S <notifications@github.com>님이 작성:

**Comment by joonseolee** [comment]
네 말씀해주셔서 감사합니다 :)
